kind: ArchiveUploadSpec
name: hello-go
include:
- hello.go
- build.sh

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: hello-go-pkg
  namespace: default
spec:
  environment:
    name: go
    namespace: default
  source:
    type: url
    url: archive://hello-go
  buildcmd: "./build.sh"
status:
  buildstatus: pending

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: hello-go
  namespace: default
spec:
  environment:
    name: go
    namespace: default
  package:
    functionName: Handler
    packageref:
      name: hello-go-pkg
      namespace: default
